server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: studentCircuitBreaker
                fallbackUri: forward:/fallback/students

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: courseCircuitBreaker
                fallbackUri: forward:/fallback/courses


management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
