server:
  port: 8765

spring:
  application:
    name: api-gateway  # Registers as "api-gateway" in Eureka
  cloud:
    gateway:
      routes:
        # =============================
        # Student Service Route
        # =============================
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**
          filters:
            - name: CircuitBreaker
              args:
                name: studentCircuitBreaker
                fallbackUri: forward:/fallback/students

        # =============================
        # Course Service Route
        # =============================
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
          filters:
            - name: CircuitBreaker
              args:
                name: courseCircuitBreaker
                fallbackUri: forward:/fallback/courses

      # =============================
      # Discovery Locator Configuration
      # =============================
      discovery:
        locator:
          enabled: false  # Keep false since explicit routes are defined

# =============================
# Management & Actuator
# =============================
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true

# =============================
# Resilience4j Circuit Breaker Config
# =============================
resilience4j:
  circuitbreaker:
    instances:
      studentCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

      courseCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

# =============================
# Eureka Client Configuration
# =============================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  # Recommended for containerized environments
