server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: studentCircuitBreaker
                fallbackUri: forward:/fallback/students

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: courseCircuitBreaker
                fallbackUri: forward:/fallback/courses

  application:
    name: gateway-service  # Recommended: Set an application name for Eureka registration

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true

resilience4j:  # Added for CircuitBreaker configuration (required for functionality)
  circuitbreaker:
    instances:
      studentCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
      courseCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true  # Recommended: Explicitly enable registration
    fetch-registry: true  # Recommended: Explicitly enable fetching registry
  instance:
    prefer-ip-address: true  # Recommended for containerized environments
