server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courseMicro_db?createDatabaseIfNotExist=true
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
