server:
  port: 8081

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://localhost:3306/courseMicro_db?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# =============================
# Management & Actuator
# =============================
management:
  endpoints:
    web:
      exposure:
        include: "*"

# =============================
# Eureka Client Configuration
# =============================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true   #  Explicit registration
    fetch-registry: true         #  Fetch registry for discovery
  instance:
    prefer-ip-address: true      #  Use IP address instead of hostname
