server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentMicro_db?createDatabaseIfNotExist=true
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
resilience4j:
  circuitbreaker:
    instances:
      courseService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

  retry:
    instances:
      courseService:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
